language: generic
dist: xenial

notifications:
  email: false

env:
  - GITBOOK_VERSION=3.2.3

cache:
  ccache: true
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/.cache
    - $TRAVIS_BUILD_DIR/node_modules

before_install:
  - nvm install node
  - node --version

install:
  - npm install -g gitbook-summary
  - npm install -g gitbook-cli

script:
  - cd Notes && book sm -t 'Notes' && cd -
  - mv assets Notes
  - mv styles Notes
  - gitbook fetch latest
  - gitbook -v $GITBOOK_VERSION install
  - gitbook -v $GITBOOK_VERSION build
  - cp Notes/assets/CNAME _book

before_deploy:
  #Ensure we are in the right dir
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  local_dir: _book
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
