language: generic
dist: xenial

notifications:
  email: false

env:
  global:
    - RUST_TEST_NOCAPTURE=1
    - RUST_BACKTRACE=1
    - GITBOOK_VERSION=3.2.3

cache:
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/.cache
    - $HOME/.cargo
    - $HOME/.rustup

before_script:
  - nvm install node
  - node --version
  - curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain stable --profile minimal
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup default stable
  - cargo install cargo-update || echo "cargo update exists!"
  - cargo install book-summary || echo "book-summary exists!"
  - cargo install-update -a
  - npm install -g gitbook-cli

script:
  - book-summary -n Notes -f git -y -s tech personal travel
  - cat Notes/SUMMARY.md
  - mv assets Notes
  - mv styles Notes
  - gitbook fetch latest
  - gitbook -v $GITBOOK_VERSION install
  - gitbook -v $GITBOOK_VERSION build
  - cp Notes/assets/CNAME _book

before_deploy:
  #Ensure we are in the right dir
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  local_dir: _book
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
