language: generic
dist: xenial

notifications:
  email: false

env:
  global:
    - RUST_TEST_NOCAPTURE=1
    - RUST_BACKTRACE=1

cache:
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/.cache
    - $HOME/.cargo
    - $HOME/.rustup

before_script:
  - curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain stable --profile minimal
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup default stable
  - cargo install cargo-update || echo "cargo update exists!"
  - cargo install mdbook || echo "mdbook exists!"
  - cargo install-update -a

script:
  - mdbook build
  - cp assets/CNAME book

before_deploy:
  #Ensure we are in the right dir
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  local_dir: book
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
